FROM nightling/base

RUN yum -y install \
	{openssl,python{3,},ruby}-devel \
	automake \
	bison \
	clang \
	cvs \
	flex \
	gcc-c++ \
	git \
	nasm \
	patchutils \
	rpm-build \
	subversion \
	&& yum clean all
